# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      # - FABRIC_LOGGING_SPEC=INFO:comm.grpc.server=fatal:stateleveldb=debug
      # - FABRIC_LOGGING_SPEC=INFO:valimpl,statebasedval,kvledger,valinternal,committer,committer.txvalidator,lockbasedtxmgr,discovery.endorsement=debug
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - FPGA_MOCK=1
      - FPGA_SERVER_ADDR=127.0.0.1:10000
    volumes:
      - ../../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: ./peer node start
