# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer0.org2.example.com:

networks:
  net_byfn:
    # external: true
    driver: overlay
    attachable: true

# x-peer-base:
#   &default-peer # environment and volume doesn't take effect here. 
#   tty: true
#   stdin_open: true
#   image: hyperledger/fabric-peer:latest
#   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#   command: /bin/bash # peer node start

services:

  zookeeper:
    image: hyperledger/fabric-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      net_byfn:
        aliases:
          - zookeeper.example.com
    deploy:
      # resources:
      #   limits:
      #     cpus: '0.90'
      #     memory: 25G
      #   reservations:
      #     cpus: '0.10'
      #     memory: 20G
      placement:
        constraints: [node.hostname == bingsu-sw11]

  kafka:
    image: hyperledger/fabric-kafka:latest
    depends_on:
    - zookeeper.example.com
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.example.com:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka.example.com:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_MESSAGE_MAX_BYTES=1048576000 # 1000 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576000 # 1000 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
    networks:
      net_byfn:
        aliases:
          - kafka.example.com
    deploy:
      # resources:
      #   limits:
      #     cpus: '0.90'
      #     memory: 25G
      #   reservations:
      #     cpus: '0.10'
      #     memory: 20G
      placement:
        constraints: [node.hostname == bingsu-sw11]

  orderer:
    image: hyperledger/fabric-orderer:latest
    tty: true
    stdin_open: true
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer # /bin/bash # 
    volumes:
      - /dev/:/dev/
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      net_byfn:
        aliases:
          - orderer.example.com
    deploy:
      # resources:
      #   limits:
      #     cpus: '0.90'
      #     memory: 25G
      #   reservations:
      #     cpus: '0.10'
      #     memory: 20G
      placement:
        constraints: [node.hostname == bingsu-sw11]


  peer0org1:
    # << : *default-peer
    tty: true
    stdin_open: true
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: ./peer_stdvcc node start # /bin/bash # 

    environment:
      # common environment
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_net_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # specific environment
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - FPGA_MOCK=1
      # - FPGA_SERVER_ADDR=172.17.0.1:50021
      - FPGA_SERVER_ADDR=127.0.0.1:10000
    volumes:
      - /dev/:/dev/
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.example.com:/var/hyperledger/production
      - ../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      net_byfn:
        aliases:
          - peer0.org1.example.com
    deploy:
      # resources:
      #   limits:
      #     cpus: '0.90'
      #     memory: 60G
      #   reservations:
      #     cpus: '0.80'
      #     memory: 50G
      placement:
        constraints: [node.hostname == bingsu-sw12]

  peer0org2:
    # << : *default-peer
    tty: true
    stdin_open: true
    image: hyperledger/fabric-peer:latest
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: ./peer_stdvcc node start # /bin/bash # 
    
    environment:
      # common environment
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_net_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # specific environment
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - FPGA_MOCK=1
      # - FPGA_SERVER_ADDR=172.17.0.1:50021
      - FPGA_SERVER_ADDR=127.0.0.1:10000
    volumes:
      - /dev/:/dev/
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.example.com:/var/hyperledger/production
      - ../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      net_byfn:
        aliases:
          - peer0.org2.example.com
    deploy:
      # resources:
      #   limits:
      #     cpus: '0.90'
      #     memory: 60G
      #   reservations:
      #     cpus: '0.80'
      #     memory: 50G
      placement:
        constraints: [node.hostname == bingsu-sw13]

  cli:
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /dev/:/dev/
      - /var/run/:/host/var/run/
      - ../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ../../payment-demo:/opt/gopath/src/github.com/hyperledger/fabric/peer/payment-demo
    networks:
      net_byfn:
        aliases:
          - cli.example.com
    deploy:
      # resources:
      #   limits:
      #     cpus: '1.00'
      #     memory: 5G
      #   reservations:
      #     cpus: '0.00'
      #     memory: 2G
      placement:
        constraints: [node.hostname == bingsu-sw11] # the same as coordinator of the swarm cluster
