# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:
  peer0.org2.example.com:
  peer1.org2.example.com:

networks:
  net_byfn:
    external: true

x-peer-base:
  &default-peer
  image: hyperledger/fabric-peer:$IMAGE_TAG
  environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    # the following setting starts chaincode containers on the same
    # bridge network as the peers
    # https://docs.docker.com/compose/networking/
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
    - FABRIC_LOGGING_SPEC=INFO:statebasedval,fpga=debug
    # - FABRIC_LOGGING_SPEC=INFO:comm.grpc.server=fatal:stateleveldb=debug
    # - FABRIC_LOGGING_SPEC=INFO:valimpl,statebasedval,kvledger,valinternal,committer,committer.txvalidator,lockbasedtxmgr,discovery.endorsement=debug
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - FPGA_MOCK=0
    # - FPGA_SERVER_ADDR=172.17.0.1:50021
    - FPGA_SERVER_ADDR=127.0.0.1:10000
  volumes:
    - /home/docker/demo/fabric-network/bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  command: peer node start

services:

  # orderer.example.com:
  orderer:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - "constraint:node==manager1"
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - /home/docker/demo/fabric-network/first-network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - /home/docker/demo/fabric-network/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - /home/docker/demo/fabric-network/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - net_byfn

  # peer0.org1.example.com:
  org1:
    << : *default-peer
    environment:
      - "constraint:node==worker1"
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=org1:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - net_byfn

  # peer1.org1.example.com:
  #   << : *default-peer
  #   environment:
  #     - CORE_PEER_ID=peer1.org1.example.com
  #     - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
  #     - CORE_PEER_LOCALMSPID=Org1MSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
  #       - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
  #       - peer1.org1.example.com:/var/hyperledger/production
  #   ports:
  #     - 8051:7051
  #     - 8053:7053
  #   networks:
  #     - net_byfn

  # peer0.org2.example.com:
  org2:
    << : *default-peer
    environment:
      - "constraint:node==worker2"
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=org2:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=org2:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=org2:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    networks:
      - net_byfn

  # peer1.org2.example.com:
  #   << : *default-peer
  #   environment:
  #     - CORE_PEER_ID=peer1.org2.example.com
  #     - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
  #     - CORE_PEER_LOCALMSPID=Org2MSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
  #       - /home/docker/demo/fabric-network/first-network/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls
  #       - peer1.org2.example.com:/var/hyperledger/production
  #   ports:
  #     - 10051:7051
  #     - 10053:7053
  #   networks:
  #     - net_byfn

  cli:
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - "constraint:node==manager1"
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /dev/:/dev/
        - /var/run/:/host/var/run/
        - /home/docker/demo/fabric-network//chaincode/:/opt/gopath/src/github.com/chaincode
        - /home/docker/demo/fabric-network/first-network/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - /home/docker/demo/fabric-network/first-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - /home/docker/demo/fabric-network/first-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - /home/docker/demo/payment-demo:/opt/gopath/src/github.com/hyperledger/fabric/peer/payment-demo
    depends_on:
      - orderer
      - org1
      - org2
    networks:
      - net_byfn
